[pytest]
markers =
    smoke: quick critical tests
    regression: full regression tests
    positive: positive test scenarios
    negative: negative test scenarios

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s